/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicConsultationRouteImport } from './routes/api/public/consultation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConsultationRoute = ApiPublicConsultationRouteImport.update({
  id: '/api/public/consultation',
  path: '/api/public/consultation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/consultation': typeof ApiPublicConsultationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/consultation': typeof ApiPublicConsultationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/consultation': typeof ApiPublicConsultationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/consultation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/consultation'
  id: '__root__' | '/' | '/api/public/consultation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicConsultationRoute: typeof ApiPublicConsultationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consultation': {
      id: '/api/public/consultation'
      path: '/api/public/consultation'
      fullPath: '/api/public/consultation'
      preLoaderRoute: typeof ApiPublicConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicConsultationRoute: ApiPublicConsultationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
