/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as ServicesAiProductReviewRouteImport } from './routes/services.ai-product-review'
import { Route as ServicesLegalSupportRouteImport } from './routes/services.legal-support'
import { Route as ServicesMvpReviewRouteImport } from './routes/services.mvp-review'
import { Route as ServicesProductAuditRouteImport } from './routes/services.product-audit'
import { Route as ServicesProductDiscoveryRouteImport } from './routes/services.product-discovery'
import { Route as ServicesProductStrategyRouteImport } from './routes/services.product-strategy'
import { Route as ApiPublicConsultationRouteImport } from './routes/api/public/consultation'
import { Route as ApiPublicQuestionRouteImport } from './routes/api/public/question'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiProductReviewRoute = ServicesAiProductReviewRouteImport.update({
  id: '/services/ai-product-review',
  path: '/services/ai-product-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLegalSupportRoute = ServicesLegalSupportRouteImport.update({
  id: '/services/legal-support',
  path: '/services/legal-support',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMvpReviewRoute = ServicesMvpReviewRouteImport.update({
  id: '/services/mvp-review',
  path: '/services/mvp-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProductAuditRoute = ServicesProductAuditRouteImport.update({
  id: '/services/product-audit',
  path: '/services/product-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesProductDiscoveryRoute =
  ServicesProductDiscoveryRouteImport.update({
    id: '/services/product-discovery',
    path: '/services/product-discovery',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesProductStrategyRoute = ServicesProductStrategyRouteImport.update({
  id: '/services/product-strategy',
  path: '/services/product-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConsultationRoute = ApiPublicConsultationRouteImport.update({
  id: '/api/public/consultation',
  path: '/api/public/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuestionRoute = ApiPublicQuestionRouteImport.update({
  id: '/api/public/question',
  path: '/api/public/question',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ai-product-review': typeof ServicesAiProductReviewRoute
  '/services/legal-support': typeof ServicesLegalSupportRoute
  '/services/mvp-review': typeof ServicesMvpReviewRoute
  '/services/product-audit': typeof ServicesProductAuditRoute
  '/services/product-discovery': typeof ServicesProductDiscoveryRoute
  '/services/product-strategy': typeof ServicesProductStrategyRoute
  '/api/public/consultation': typeof ApiPublicConsultationRoute
  '/api/public/question': typeof ApiPublicQuestionRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ai-product-review': typeof ServicesAiProductReviewRoute
  '/services/legal-support': typeof ServicesLegalSupportRoute
  '/services/mvp-review': typeof ServicesMvpReviewRoute
  '/services/product-audit': typeof ServicesProductAuditRoute
  '/services/product-discovery': typeof ServicesProductDiscoveryRoute
  '/services/product-strategy': typeof ServicesProductStrategyRoute
  '/api/public/consultation': typeof ApiPublicConsultationRoute
  '/api/public/question': typeof ApiPublicQuestionRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/services/ai-product-review': typeof ServicesAiProductReviewRoute
  '/services/legal-support': typeof ServicesLegalSupportRoute
  '/services/mvp-review': typeof ServicesMvpReviewRoute
  '/services/product-audit': typeof ServicesProductAuditRoute
  '/services/product-discovery': typeof ServicesProductDiscoveryRoute
  '/services/product-strategy': typeof ServicesProductStrategyRoute
  '/api/public/consultation': typeof ApiPublicConsultationRoute
  '/api/public/question': typeof ApiPublicQuestionRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/privacy'
    | '/sitemap.xml'
    | '/insights/$slug'
    | '/services/ai-product-review'
    | '/services/legal-support'
    | '/services/mvp-review'
    | '/services/product-audit'
    | '/services/product-discovery'
    | '/services/product-strategy'
    | '/api/public/consultation'
    | '/api/public/question'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/privacy'
    | '/sitemap.xml'
    | '/insights/$slug'
    | '/services/ai-product-review'
    | '/services/legal-support'
    | '/services/mvp-review'
    | '/services/product-audit'
    | '/services/product-discovery'
    | '/services/product-strategy'
    | '/api/public/consultation'
    | '/api/public/question'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/privacy'
    | '/sitemap.xml'
    | '/insights/$slug'
    | '/services/ai-product-review'
    | '/services/legal-support'
    | '/services/mvp-review'
    | '/services/product-audit'
    | '/services/product-discovery'
    | '/services/product-strategy'
    | '/api/public/consultation'
    | '/api/public/question'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  ServicesAiProductReviewRoute: typeof ServicesAiProductReviewRoute
  ServicesLegalSupportRoute: typeof ServicesLegalSupportRoute
  ServicesMvpReviewRoute: typeof ServicesMvpReviewRoute
  ServicesProductAuditRoute: typeof ServicesProductAuditRoute
  ServicesProductDiscoveryRoute: typeof ServicesProductDiscoveryRoute
  ServicesProductStrategyRoute: typeof ServicesProductStrategyRoute
  ApiPublicConsultationRoute: typeof ApiPublicConsultationRoute
  ApiPublicQuestionRoute: typeof ApiPublicQuestionRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-product-review': {
      id: '/services/ai-product-review'
      path: '/services/ai-product-review'
      fullPath: '/services/ai-product-review'
      preLoaderRoute: typeof ServicesAiProductReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/legal-support': {
      id: '/services/legal-support'
      path: '/services/legal-support'
      fullPath: '/services/legal-support'
      preLoaderRoute: typeof ServicesLegalSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/mvp-review': {
      id: '/services/mvp-review'
      path: '/services/mvp-review'
      fullPath: '/services/mvp-review'
      preLoaderRoute: typeof ServicesMvpReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/product-audit': {
      id: '/services/product-audit'
      path: '/services/product-audit'
      fullPath: '/services/product-audit'
      preLoaderRoute: typeof ServicesProductAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/product-discovery': {
      id: '/services/product-discovery'
      path: '/services/product-discovery'
      fullPath: '/services/product-discovery'
      preLoaderRoute: typeof ServicesProductDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/product-strategy': {
      id: '/services/product-strategy'
      path: '/services/product-strategy'
      fullPath: '/services/product-strategy'
      preLoaderRoute: typeof ServicesProductStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/consultation': {
      id: '/api/public/consultation'
      path: '/api/public/consultation'
      fullPath: '/api/public/consultation'
      preLoaderRoute: typeof ApiPublicConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/question': {
      id: '/api/public/question'
      path: '/api/public/question'
      fullPath: '/api/public/question'
      preLoaderRoute: typeof ApiPublicQuestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  ServicesAiProductReviewRoute: ServicesAiProductReviewRoute,
  ServicesLegalSupportRoute: ServicesLegalSupportRoute,
  ServicesMvpReviewRoute: ServicesMvpReviewRoute,
  ServicesProductAuditRoute: ServicesProductAuditRoute,
  ServicesProductDiscoveryRoute: ServicesProductDiscoveryRoute,
  ServicesProductStrategyRoute: ServicesProductStrategyRoute,
  ApiPublicConsultationRoute: ApiPublicConsultationRoute,
  ApiPublicQuestionRoute: ApiPublicQuestionRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
